env: http_proxy=http://proxy.wdf.sap.corp:8080 HTTP_PROXY=http://proxy.wdf.sap.corp:8080 https_proxy=http://proxy.wdf.sap.corp:8080 HTTPS_PROXY=http://proxy.wdf.sap.corp:8080 ftp_proxy=http://proxy.wdf.sap.corp:8080 FTP_PROXY=http://proxy.wdf.sap.corp:8080 no_proxy="*.local,169.254/16,*.sap.corp,*.corp.sap" NO_PROXY="*.local,169.254/16,*.sap.corp,*.corp.sap"
language: node_js
node_js:
  - "0.10.38"
  - "0.12.4"
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt dist
